# Project
site_name: nemo-simsar
#site_url: http://127.0.0.1:8000
site_url: http://mscheinert.github.io/simsar
site_author: Markus Scheinert and Lucienne Micallef
site_description: >-
  Document and share your NEMO ocean model simulation

# Repository
repo_name: nemo-simsar on GitHub
repo_url: https://github.com/immerse-project/nemo-simsar
edit_uri: ""
use_directory_urls: false

# Copyright
copyright: Copyright &copy; 2020 Markus Scheinert

theme:
  name: material
  logo: 'docs/img/simsar_logo.png'
  favicon: 'docs/img/simsar_logo.ico'
  palette:
    scheme: default
    primary: light green
    accent: deep orange
  features:
    - tabs
    - search.highlight
  icon:
    repo: fontawesome/brands/github

extra_css:
    - extra.css
    
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.tabbed
  - toc:
      permalink: "🔗"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Plugins
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                setup_commands:
                - import sys
                - sys.path.append("src")
                rendering:
                    show_source: false  
        custom_templates: templates
        watch:
            - src/my_package


# Navigation
nav:
    - 'HOME': 
        - 'index.md'
    - 'User Guide': 
        - 'overview.md'
        - 'gettingstarted.md'
        - 'Citable Input Data':
            - 'How to refer to Input Data': 'inputdata.md'
            - 'The "input.def" file': 'input_def.md'
        - 'The Simulation Package': 
            - 'Simulation Meta Data': ''
            - 'Create a README (mkReadme)': 'mkReadme.md'
            - 'Bundle up': 'bundleup.md'
        - 'Publish': 
            - 'Persistent Handler (DOI)': ''
            - 'publish via git': 'publish_git.md'
            - 'add static webpage (git pages)': 'publish_gitpages.md'
        - 'Obtain a Simulation Package': 
            'file exchange': 'getviacloud.md'
            'git': 'getviagit.md'
            'HTML (git pages)': 'getvianemo.md'
            'others': 'getothers.md'
    - 'API Reference':
        - 'api-mkreadme.md'
    #- '🡽 IMMERSE Project':
    #    - 'https://immerse-ocean.eu'
    #- '🡽 NEMO-OCEAN':
    #    - 'https://www.nemo-ocean.eu'


#pages:
    #- 'notes.md'
